Add option to pass abort signal
SaxoBank/openapi-clientlib-js pull request #393
Opened 2021-05-07 13:19 UTC by sobstel

We sometimes (eg when user logs out while requests are being made) need to abort fetch requests. This PR adds possibility to use abort signal (returned by AbortController), so it can be handled without hacks.

2021-05-10 08:13 UTC, michax requested changes

2021-05-12 17:05 UTC, sobstel commented on src/utils/fetch.js
> +    return fetch(url, { headers, method, body, credentials, signal })
`fetch` is not supported by IE11 at all

2021-05-13 09:55 UTC, michax commented on src/utils/fetch.js
> +    return fetch(url, { headers, method, body, credentials, signal })
Quite vague comment on my end, quite rushed, sorry.
Anyhow, all my worries regarding IE11, polyfill etc can be solved on library consumer side.

2021-05-13 09:56 UTC, michax approved these changes

2021-05-13 10:06 UTC, michax requested changes

2021-05-13 10:06 UTC, michax commented on src/openapi/transport/core.spec.js
> +    describe('abort signal', () => {
Nitpick. Let's fix prettier errors.

![image](https://user-images.githubusercontent.com/117785/118111179-a14c1c80-b3e3-11eb-8703-69834a5abb59.png)

2021-05-13 10:16 UTC, michax commented on src/openapi/transport/core.spec.js
> +    describe('abort signal', () => {
Resolved it as part of preparing beta build/

2021-05-13 10:16 UTC, michax approved these changes

2021-05-20 13:18 UTC, merged